var LIST_MECHANICS = [
	{ type: "MECHANICS", variable: "a", definition: "acceleration" },
	{ type: "MECHANICS", variable: "v", definition: "velocity" },
	{ type: "MECHANICS", variable: "K", definition: "kinetic energy" },
	{ type: "MECHANICS", variable: "r", definition: "distance" },
	{ type: "MECHANICS", variable: "x", definition: "position" },
	{ type: "MECHANICS", variable: "P", definition: "power" },
	{ type: "MECHANICS", variable: "l", definition: "length" },
	{ type: "MECHANICS", variable: "N", definition: "normal force" },
	{ type: "MECHANICS", variable: "J", definition: "impulse" },
	{ type: "MECHANICS", variable: "W", definition: "work" },
	{ type: "MECHANICS", variable: "&omega;", definition: "angular speed" },
	{ type: "MECHANICS", variable: "&theta;", definition: "angle" },
	{ type: "MECHANICS", variable: "<strong style='color: black;'>r</strong>", definition: "position vector" },
	{ type: "MECHANICS", variable: "T", definition: "period" },
	{ type: "MECHANICS", variable: "t", definition: "time" },
	{ type: "MECHANICS", variable: "F", definition: "force" },
	{ type: "MECHANICS", variable: "h", definition: "height" },
	{ type: "MECHANICS", variable: "I", definition: "rotational inertia" },
	{ type: "MECHANICS", variable: "&mu;", definition: "coefficient of friction" },
	{ type: "MECHANICS", variable: "U", definition: "potential energy" },
	{ type: "MECHANICS", variable: "p", definition: "momentum" },
	{ type: "MECHANICS", variable: "f", definition: "frequency" },
	{ type: "MECHANICS", variable: "k", definition: "spring constant" },
	{ type: "MECHANICS", variable: "&alpha;", definition: "angular acceleration" },
	{ type: "MECHANICS", variable: "&tau;", definition: "torque" },
	{ type: "MECHANICS", variable: "m", definition: "mass" },
	{ type: "MECHANICS", variable: "L", definition: "angular momentum" }
];

var LIST_UNITS = [
	{ type: "UNITS", variable: "m", definition: "meter" },
	{ type: "UNITS", variable: "W", definition: "watt" },
	{ type: "UNITS", variable: "Hz", definition: "hertz" },
	{ type: "UNITS", variable: "F", definition: "farad" },
	{ type: "UNITS", variable: "J", definition: "joule" },
	{ type: "UNITS", variable: "mol", definition: "mole" },
	{ type: "UNITS", variable: "T", definition: "tesla" },
	{ type: "UNITS", variable: "Pa", definition: "pascal" },
	{ type: "UNITS", variable: "N", definition: "newton" },
	{ type: "UNITS", variable: "K", definition: "kelvin" },
	{ type: "UNITS", variable: "&deg;C", definition: "degrees in celcius" },
	{ type: "UNITS", variable: "eV", definition: "electron-volt" },
	{ type: "UNITS", variable: "A", definition: "ampere" },
	{ type: "UNITS", variable: "s", definition: "second" },
	{ type: "UNITS", variable: "&Omega;", definition: "ohm" },
	{ type: "UNITS", variable: "V", definition: "volt" },
	{ type: "UNITS", variable: "C", definition: "coulomb" },
	{ type: "UNITS", variable: "kg", definition: "kilogram" },
	{ type: "UNITS", variable: "H", definition: "henry" }
];

var LIST_ELECTRICITY_AND_MAGNETISM = [
	{ type: "ELECTRICITY & MAGNETISM", variable: "A", definition: "area" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "B", definition: "magnetic field" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "C", definition: "capacitance" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "d", definition: "distance" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "E", definition: "electric field" },
	// { type: "ELECTRICITY & MAGNETISM", variable: "\mathcal{E}", definition: "emf" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "F", definition: "force" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "I", definition: "current" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "L", definition: "inductance" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "l", definition: "length" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "n", definition: "number of loops of wire per unit length" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "P", definition: "power" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "Q", definition: "charge" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "q", definition: "point charge" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "R", definition: "resistance" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "r", definition: "distance" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "t", definition: "time" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "U", definition: "potential or stored energy" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "V", definition: "electrical potential" },
	// { type: "ELECTRICITY & MAGNETISM", variable: "\mathcal{V}", definition: "velocity" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "p", definition: "resistivity" },
	{ type: "ELECTRICITY & MAGNETISM", variable: "&Phi;m", definition: "magnetic flux" },
	// { type: "ELECTRICITY & MAGNETISM", variable: "\mathcal{k}", definition: "dielectric constant" }
];